BASE_URL="https://tobeto.com"
ANASAYFA_IFRAME="//*[@id='exw-launcher-frame']"
CHATBOT_IFRAME="//*[@id='launcher']/div"
CHATBOT_SECOND_IFRAME="//*[@id='exw-conversation-frame']"
SIMGE_DURUMU_FRAME= ".exw-minimize-button > path:nth-child(2)"
KONUSMA_BITIRME_CSSSELECTOR=".exw-end-session-button > path"
SIMGE_DURUMU_CSSSELECTOR=".finishSessionCheckButtons > button:nth-child(1)"
MESSAGE_KEY="message"
MESSAGE_NAME="message"
SEND_KEY="//*[@id='exw-conversation-frame-body']/div/div/div/div[3]/form/div/button"
TOBETO_HAKKINDA=".exw-reply:nth-child(1)"
EGITIMLERIMIZ=".exw-reply:nth-child(1)"
HANGI_EGITIMLER=".exw-reply:nth-child(1)"