LOGIN_URL="https://tobeto.com/giris"
CALENDAR_CSS=".calendar-btn"
CALENDAR_TEXT_XPATH="//span[text()='Eğitim ve Etkinlik Takvimi']"
SEARCH_EDUCATION_XPATH="//input[@placeholder='Eğitim arayın...']"
SEARCH_EDUCATION_TEXT="Yazılım Kalite ve Test"
QUALITY_TEST_XPATH="(//span[@class='text-truncate'])[1]"   
INSTRUCTOR_CLASS=" css-1xc3v61-indicatorContainer"
SEARCH_INSTRUCTOR_TEXT="İrem Balcı"
INSTRUCTOR_XPATH="(//span[@class='text-truncate'])[2]"
END_LESSONS_XPATH="//input[@name='eventEnded']"
CONTINUE_LESSONS_XPATH="//input[@name='eventContinue']"
BUY_LESSONS_XPATH="//input[@name='eventBuyed']"
NOT_STARTED_LESSONS_XPATH="//input[@name='eventNotStarted']"
MONTH_XPATH="//button[@title='Ay']"
WEEK_XPATH="//button[@title='Hafta']"
DAY_XPATH="//button[@title='Gün']"
RIGHT_KEYS_CLASS="//button[@title='ileri']"
LEFT_KEYS_CLASS="//button[@title='geri']"
CLOSE_BUTTON_XPATH="//button[@class='btn-close btn-close-white']"
CODE_ACADEMY_XPATH="(//a[text()='Codecademy'])[1]"