BASE_URL="https://tobeto.com"
PROFIL_BILGILERIM_URL="https://tobeto.com/profilim/profilimi-duzenle/kisisel-bilgilerim"
LOGIN_TOBETO_XLSX="data/loginTobeto.xlsx"
LOGIN_BUTTON_XPATH="//*[@id='offcanvasExample']/div[2]/div[2]/div/a[1]"
LOGIN_BUTTON_CLICK_XPATH="//*[@id='__next']/div/main/section/div/div/div[1]/div/form/button"
E_MAIL= "email"
PASSWORD_NAME = "password"
EGITIMLERIM_URL="https://www.tobeto.com/egitimlerim"
DEVAM_ETTIGIMEGITIMLER="//*[@id='started-tab']"
TAMAMLADIGIM_EGITIMLER="//*[@id='done-lessons-tab']"
ARAMA_KUTUSU="//*[@id='search']"
KURUM_SECIMI_TIK="//*[@id='__next']/div/main/div[2]/div[1]/div/div[2]/div/div[1]/div[2]/div"
SIRILAMA_SECIM_TIK="//*[@id='__next']/div/main/div[2]/div[1]/div/div[3]/div/div/div[2]/div"
FILTRE_KALDIR_IKON="//*[@id='__next']/div/main/div[2]/div[1]/div/div[4]/button"
GIRILEN_METINILE_ARAMA="//*[@id='react-select-3-input']"
EGITIME_GIT="//*[@id='all-lessons-tab-pane']/div/div[2]/div/div[2]/a"