#GİRİŞ/KAYITOLMA/PROFİLDENEYİM
URL = "https://tobeto.com/giris"
URL_BASIC = "https://tobeto.com/"
giriş_xlsx = "data/giris.xlsx"
register_xlsx = "data/register.xlsx"
trying_xlsx= "data/trying.xlsx"
name = "//*[@id='__next']/div/main/section/div/div/div[1]/div/form/input[1]"
password = "password"
PASSWORD_XPATH = "//*[@id='__next']/div/main/section/div/div/div[1]/div/form/input[2]"
password_input = "//*[@id='__next']/div/main/section/div/div/div[1]/div/form/input[2]"
LOGGİNBUTTON_XPATH= "//*[@id='__next']/div/main/section/div/div/div[1]/div/form/button"
KAYIT_OL = "//*[@id='__next']/div/main/section/div/div/div[1]/div/div[2]/label/small/a"
KAYIT_NAME="//*[@id='__next']/div/main/section/div/div/div[1]/div/div/form/input[1]"
KAYIT_LASTNAME="//*[@id='__next']/div/main/section/div/div/div[1]/div/div/form/input[2]"
KAYIT_EPOSTA="//*[@id='__next']/div/main/section/div/div/div[1]/div/div/form/input[3]"
KAYIT_SİFRE="//*[@id='__next']/div/main/section/div/div/div[1]/div/div/form/input[4]"
KAYIT_SİFRE_AGAİN="//*[@id='__next']/div/main/section/div/div/div[1]/div/div/form/input[5]"
ACIK_RIZA_METNİ = "/html/body/div[4]/div/div/div/div/div/label[2]/small/input"
UYELIK_SOZLESMESİ= "/html/body/div[4]/div/div/div/div/div/label[3]/small/input"
EPOSTA_İZİN= "/html/body/div[4]/div/div/div/div/div/label[4]/small/label[1]/input"
ARAMA_İZİN= "/html/body/div[4]/div/div/div/div/div/label[4]/small/label[2]/input"
PHONEE = "//*[@id='phoneNumber']"
ROBOT= "/html/body/div[4]/div/div/div/div/div/div[3]/button[2]"
DEVAM_ET_BUTTON= "/html/body/div[4]/div/div/div/div/div/div[3]/button[2]"
IFRAME= "//iframe[@title='reCAPTCHA']"
PROFILE_XPATH = "//*[@id='__next']/div/nav/div[1]/div/div/div[2]/button"
INFORMATİON_PROFILE= "//*[@id='__next']/div/nav/div[1]/div/div/div[2]/ul/li[1]/a" 
EXPERINCE_XPATH = "//*[@id='__next']/div/main/section/div/div/div[1]/div/a[2]/span[2]"
KURUM_ADI= "input-label-text"
POZISYON = "//*[@id='__next']/div/main/section/div/div/div[2]/form/div/div[2]/label"
SEKTOR = "//*[@id='__next']/div/main/section/div/div/div[2]/form/div/div[3]/label"
SEHİR_SECİNİZ ="//*[@id='__next']/div/main/section/div/div/div[2]/form/div/div[4]/label"
İS_BASLANGICI = "//*[@id='__next']/div/main/section/div/div/div[2]/form/div/div[5]/label"
İS_BİTİS = "//*[@id='__next']/div/main/section/div/div/div[2]/form/div/div[6]/label[1]"
İS_ACIKLAMASI = "//*[@id='__next']/div/main/section/div/div/div[2]/form/div/div[7]/label"
KAYDET_BUTTON= "//*[@id='__next']/div/main/section/div/div/div[2]/form/button"
ZORUNLU_ALAN= "text-danger"
KAMPUS_365= "//*[@id='__next']/div/main/section/div/div/div[2]/form/div/div[1]/input"
kaydet_button = "//*[@id='__next']/div/main/section/div/div/div[2]/form/button"
DESCRIPTION_BUSİNESS = "//textarea[contains(@class, 'tobeto-input')]"
MORETHANTHREEHUNDERED = ".col-md-12 > .text-danger"
SAVE_BUTTON= "//button[contains(@class, 'btn-primary') and contains(@class, 'mobil-btn')]"
CONTİNUE_WORK_CHECKBOX = "//*[@id='__next']/div/main/section/div/div/div[2]/form/div/div[6]/label[2]/input"
DAY_ELEMENT_FINISH = ".react-datepicker__day.react-datepicker__day--010"
OPTION_YEAR_FINISH = "//select[@class='react-datepicker__year-select']/option[text()='1992']"
SELECT_YEAR_FINISH = "react-datepicker__year-select "
OPTION_OCAK_FINISH = "//select[@class='react-datepicker__month-select']/option[text()='Ocak']"
SELECT_MOUNTH_FINISH = "//*[@id='__next']/div/main/section/div/div/div[2]/form/div/div[6]/div[2]/div[2]/div/div/div[2]/div[1]/div[2]/div[1]/select"
TEXTT_FINISH_GGAAYYYY = "//*[@id='__next']/div/main/section/div/div/div[2]/form/div/div[6]/div/div/input"
DAY_ELEMENT = ".react-datepicker__day.react-datepicker__day--010"
OPTION_YEAR = "//select[@class='react-datepicker__year-select']/option[text()='1976']"
SELECT_YEAR = "react-datepicker__year-select "
OPTION_OCAK = "//select[@class='react-datepicker__month-select']/option[text()='Ocak']"
SELECT_MOUNTH = "react-datepicker__month-select"
TEXTT_GGAAYYYY= "//*[@id='__next']/div/main/section/div/div/div[2]/form/div/div[5]/div[1]/div/input"
IL_SECINIZ = "//select[@name='country']/option[text()='İl Seçiniz']"
CITY = "//*[@id='__next']/div/main/section/div/div/div[2]/form/div/div[4]/select" 
MORE_THAN_FIFTY = "//*[@id='__next']/div/main/section/div/div/div[2]/form/div/div[3]/span"
BOX_SECTOR = "//*[@id='__next']/div/main/section/div/div/div[2]/form/div/div[3]/input"
LESS_THAN_FIVE = "//*[@id='__next']/div/main/section/div/div/div[2]/form/div/div[3]/span"
BOXSECTOR = "//*[@id='__next']/div/main/section/div/div/div[2]/form/div/div[3]/input"
MORE_THAN_FIFTY_CASE4 = "//*[@id='__next']/div/main/section/div/div/div[2]/form/div/div[2]/span"
BOX_POSİTİON = "//*[@id='__next']/div/main/section/div/div/div[2]/form/div/div[2]/input"
LESS_THAN_FIVE_CASE4 = "//*[@id='__next']/div/main/section/div/div/div[2]/form/div/div[2]/span"
BOX_POSİTİON1 = "//*[@id='__next']/div/main/section/div/div/div[2]/form/div/div[2]/input"
MORE_THAN_FIFTY_CASE3 = "//*[@id='__next']/div/main/section/div/div/div[2]/form/div/div[1]/span"
BOX1_CASE3 = "//*[@id='__next']/div/main/section/div/div/div[2]/form/div/div[1]/input"
BOX2_CASE3 = "//*[@id='__next']/div/main/section/div/div/div[2]/form/div/div[1]/input"

#Şifre Yenileme
PASSWORD_RESET = "//*[@id='__next']/div/main/section/div/div/div[1]/div/form/label/small/p"
EMAİL_SECTION = "//*[@id='__next']/div/main/section/div/div/div/input"
EMAİL_CLİCK = "//*[@id='__next']/div/main/section/div/div/div/button"
PASSWORD_RESET_MESSAGE = "//*[@id='__next']/div/main/div[2]/div/div[2]"
INVALİD_EMAİL = "#__next > div > main > div.mobile-width-100 > div > div.toast-body"

#PROFİLEĞİTİMLERİM
MYEDUCATIONALİFE = "//*[@id='__next']/div/main/section/div/div/div[1]/div/a[3]/span[2]"
EGITIMDURUMU = "//label[@class='input-label-text' and text()='Eğitim Durumu*']"
UNIVERSITY = "//*[@id='__next']/div/main/section/div/div/div[2]/form/div/div[2]/label"
MEZUNIYETYILI = "//*[@id='__next']/div/main/section/div/div/div[2]/form/div/div[5]/label[1]"
BOLUM = "//*[@id='__next']/div/main/section/div/div/div[2]/form/div/div[3]/label"
BASLANGICYILI = "//*[@id='__next']/div/main/section/div/div/div[2]/form/div/div[4]/label"
SAVEBUTTON = "//*[@id='__next']/div/main/section/div/div/div[2]/form/button"
UNIVERSITY_FIELD = "//*[@id='__next']/div/main/section/div/div/div[2]/form/div/div[2]/input"
EDUCATIONAL_STATUS = "//*[@id='__next']/div/main/section/div/div/div[2]/form/div/div[1]/select"
SELECT_EDUCATIONAL_STATUS = "//*[@id='__next']/div/main/section/div/div/div[2]/form/div/div[1]/select/option[4]"
ENAZIKIKARAKTER = "//*[@id='__next']/div/main/section/div/div/div[2]/form/div/div[2]/span"
UMTFİFTY = "//*[@id='__next']/div/main/section/div/div/div[2]/form/div/div[2]/span"
BOLUM_ENAZIKIKARAKTER = "//*[@id='__next']/div/main/section/div/div/div[2]/form/div/div[3]/span"
BOLUM_ENFAZLAELLIKARAKTER = "//*[@id='__next']/div/main/section/div/div/div[2]/form/div/div[3]/span"
START_YEAR = "//*[@id='__next']/div/main/section/div/div/div[2]/form/div/div[4]/div[1]/div/input"
SELECTSTARTYEAR = ".react-datepicker__year-text:nth-child(9)"
GRADUATİON = "//*[@id='__next']/div/main/section/div/div/div[2]/form/div/div[5]/div[1]/div/input"
GRADUATİON_YEAR_CHECKBOX = "//*[@id='__next']/div/main/section/div/div/div[2]/form/div/div[5]/label[2]/input"
SELECT_GRADUATIONYEAR = ".react-datepicker__year-text:nth-child(10)"
FOR = ".react-datepicker__navigation--next"
BACK= ".react-datepicker__navigation"
START_2015 = ".react-datepicker__year-text:nth-child(11)"
MEZUNIYET_GERİGELME = ".react-datepicker-ignore-onclickoutside"
MEZUNIYETYILI_SECME = ".react-datepicker__year-text:nth-child(3)"
DELETE = "//*[@id='__next']/div/main/section/div/div/div[2]/div/div/div[2]/span"
ALERT_MESSAGE = "/html/body/div[4]/div/div/div/div/div/p[1]"
YES_BUTTON = "/html/body/div[4]/div/div/div/div/div/div[2]/button[2]"


#Senkron Eğitimler
LESSONS = "//*[@id='lessons-tab']"
SHOWMORE_BUTTON = "//*[@id='lessons-tab-pane']/div/div/div[2]"
PROCEED_TO_TRAINING = "//*[@id='all-lessons-tab-pane']/div/div[14]/div/div[2]/a"
YOU_DID_IT = "#info-text-question > svg"
HOW_CAN_I_COMPLETE_TRANING = "//*[@id='info-text-question']/div/div[2]/div/div/p[1]"
HOW_CAN_I_ACHIEVE_TRANING = "//*[@id='info-text-question']/div/div[2]/div/div/p[2]"
LIKE_ICON = "main-content"
LIKE_NUMBER = "//*[@id='dynamicContent']/div/div[1]/div/div[2]/div/div[1]/div/div[2]/div/div[3]/div/div/span[2]/span"
CLOSE_WINDOW= ".anticon-close path"
USER_CLICK = "#userCardPopover-13248 .col-lg-10"
FOLLOW_SHE = ".ant-btn-primary > span"
SUCCESSFUL_FOLLOW_MESSAGE = "//*[@id='wrapper-content']/div[2]/div/div/p"
CLOSE_MESSAGE = "//*[@id='growl-item-close']"
DONT_FOLLOW_SHE = ".ant-btn-primary > span"
UNSUCCESSFUL_FOLLOW_MESSAGE = ".growl-item-content > p"
CLOSE_UNSUCCESSFUL_FOLLOW_MESSAGE= "//*[@id='growl-item-close']"
FAVORI_ICON= "//*[@id='dynamicContent']/div/div[1]/div/div[2]/div/div[1]/div/div[2]/div/div[4]/div/span"
FAVORI_ICON_MESSAGE = ".growl-item-content > p"

#Katalog Bölümü
CATALOG = "//*[@id='__next']/div/nav/div[1]/ul/li[4]/a"
SEARCH = "search"
MAGNİFYİNG_GLASS = "button:nth-child(2) > div > svg"
LESSON = ".name:nth-child(2)"
MESSAGE = ".d-flex > p"
PANEL = "#headingSeven .title"
SPECİAL_FOR_ME = ".mb-3 span"
SEARCH_BOX = "#collapseSeven .form-control"
FREE_EDUCATION= "Ücretsiz Eğitimler"
EGİTİMLERİM = "#headingFive .title"
ARAMA_KUTUSU_EGITIMLERIM = "#collapseFive .form-control"
DIJITAL_GELISIM ="Dijital Gelişim"
S_LEVEL = "#headingThree .title"
ARAMA_KUTUSU_SEVİYE = "#collapseThree .form-control"
KONU = "#headingFour .title"
KONU_ARAMAKUTUSU= "#collapseFour .form-control"
YAZILIM_DİLİ = "#headingTwo .title"
YAZILIM_DİLİ_ARAMAKUTUSU = "#collapseTwo .form-control"
EGITMEN ="#headingOne .title"
EGITMEN_ARAMAKUTUSU = "#collapseOne .form-control"
DURUM = "#headingFivee .title"
DURUM_ARAMAKUTUSU = "#collapseFivee .form-control"

#Gezinme Çubuğu
APPLYBUTTON = "//*[@id='__next']/div/main/div[1]/div/div/div[3]/button"
ISTANBUL_KODLUYOR= "//*[@id='__next']/div/div[2]/div[2]/span[1]"
LOGINBUTTON= "//*[@id='__next']/div/section[1]/nav/div/div/a[1]"
SIGNBUTTON = ".mt-6:nth-child(1)"