LOGIN_URL="https://tobeto.com/giris"
LOGIN_BUTTON_XPATH="//button[contains(.,\'Giriş Yap\')]"
WARNING_MESSAGE_XPATH="//p[contains(.,\'Doldurulması zorunlu alan*\')]"
EPOSTA_TEXT_BOX_XPATH="//input[@name=\'email\']"
PASSWORD_TEXT_BOX_XPATH="//input[@name=\'password\']"
VALID_EPOSTA="elifisci1103@gmail.com"
VALID_PASSWORD="11d1103."
POPUP_MESSAGE_CSS=".toast-body"
POPUP_MESSAGE_POSITIVE= "• Giriş başarılı."
POPUP_MESSAGE_NEGATIVE="• Geçersiz e-posta veya şifre."
WARNING_MESSAGE="Doldurulması zorunlu alan*"
INVALID_PASSWORD="11E1103K"
INVALID_EPOSTA="elifisleyen743@gmail.com"
POPUP_MESSAGE_NEGATIVE2="• Henüz e-posta adresinizi doğrulamadınız."
