LOGIN_URL="https://tobeto.com/giris"
MAIN_PAGE_LINKTEXT="Ana Sayfa"
MAIN_PAGE_URL="https://tobeto.com/platform"
PROFILE_LINK_TEXT="Profilim"
REVIEWS_LINK_TEXT="Değerlendirmeler"
CATALOG_LINK_TEXT="Katalog"
CALENDAR_LINK_TEXT="Takvim"
ISTANBUL_CODING_LINK_TEXT="İstanbul Kodluyor"
PROFILE_URL="https://tobeto.com/profilim"
REVIEWS_URL="https://tobeto.com/degerlendirmeler"
CATALOG_URL="https://tobeto.com/platform-katalog"
CALENDAR_URL="https://tobeto.com/takvim"
ISTANBUL_CODING_URL="https://tobeto.com/istanbul-kodluyor"
PROFILE_SUMMARY_CSS="span:nth-child(3) > svg"
PROFILE_INFO_XPATH="(//a[@class='dropdown-item profil-dropdown'])[1]"