PASSWORD_RESET_URL="https://tobeto.com/sifremi-unuttum"
EPOSTA_TEXT_BOX_XPATH="//input[@value=\'\']"
INVALID_EPOSTA="a@u"
SEND_BUTTON_XPATH="//button[contains(.,\'Gönder\')]"
POPUP_MESSAGE_XPATH="//div[@class='toast-body']"
INVALID_EPOSTA_MESSAGE="• Girdiğiniz e-posta geçersizdir."
VALID_EPOSTA="elifisci1103@gmail.com"
VALID_EPOSTA_MESSAGE="• Şifre sıfırlama linkini e-posta adresinize gönderdik. Lütfen gelen kutunuzu kontrol edin."
INVALID_EPOSTA2="elifisleyen743@gmail.com"
INVALID_EPOSTA_MESSAGE2="Kayıtlı eposta adresi bulunamadı"