SETTINGS_BUTTON_XPATH="(//span[@class='sidebar-text'])[8]"
CHANGE_PASSWORD_TEXT_XPATH="//button[text()='Şifre Değiştir']"
CHANGE_PASSWORD_BUTTON_CSS=".btn-primary"
REQUIRED_FILE_XPATH="//span[@class='text-danger']"
REQUIRED_FILE_TEXT="Doldurulması zorunlu alan*"
OLD_PASSWORD_NAME="currentPassword"
OLD_PASSWORD="11d1103."
NEW_PASSWORD_NAME="password"
NEW_PASSWORD="11R1103"
CONFIRM_PASSWORD_NAME= "passwordConfirmation"
CONFIRM_PASSWORD="11R1103"
INVALID_OLD_PASSWORD="11E1103."
WARNING_MESSAGE_XPATH="//div[@class='toast-body']"
INVALID_PASSWORD_WARNING="• Mevcut şifre geçersizdir."
CHARACTER_PASSWORD_WARNING="• Şifreniz en az 6 karakterden oluşmalıdır."
CHARACTER_NEW_PASSWORD="11r1"
DIF_NEW_PASSWORD="11e1186"
SUCCESS_PASSWORD_CHANGE_WARNING="• Şifreniz güncellenmiştir."
DIF_NEW_PASSWORD_WARNING="• Girilen şifreler eşleşmiyor kontrol ediniz.."
SAME_PASSWORD_WARNING="• Yeni şifreniz mevcut şifrenizden farklı olmalıdır."