

PROFILE_INF0_XPATH ="(//a[@class='dropdown-item profil-dropdown'])[1]"
PROFILE_SUMMARY_CSS="span:nth-child(3) > svg"
PROFILE_INFO_XPATH="(//a[@class='dropdown-item profil-dropdown'])[1]"
PHOTO_EDIT_ICON_CSS=".photo-edit-btn"
SEARCH_BUTTON_CSS=".uppy-c-btn"
SEARCH_BUTTON_TEXT="gözat"
CLOSE_BUTTON_XPATH="//button[@class='uppy-u-reset uppy-Dashboard-close']"
UPLOAD_XPATH="(//input[@type='file'])[1]"
REMOVE_FILE_XPATH="//button[@title='Dosyayı kaldır']"
EXPECTED_VALUE="Dosyayı kaldır"
TITLE_TEXT_POSITIVE="Title değeri doğru!"
TITLE_TEXT_NEGATIVE="Title değeri beklenenle eşleşmiyor."
UPLOAD_FILE_BUTTON_XPATH="//button[@class='uppy-u-reset uppy-c-btn uppy-StatusBar-actionBtn uppy-StatusBar-actionBtn--upload uppy-c-btn-primary']"
DUSTBIN_CSS=".photo-delete"
NO_BUTTON_XPATH="//button[contains(.,'Hayır')]"
YES_BUTTON_XPATH="//button[contains(.,'Evet')]"
WARNING_MESSAGE_CSS =".toast-body"
WARNING_MESSAGE_TEXT="• Dosya kaldırma işlemi başarılı."
NAME_BOX_NAME="name"
NAME="Elif"
SURNAME_BOX_XPATH="(//input[@class='form-control tobeto-input'])[2]"
SURNAME="KAYA"
COUNTRY_ICON_NAME="phoneNumberCountry"
COUNTRY_VISIBLE_TEXT="Almanya"
PHONE_NUMBER_ID="phoneNumber"
PHONE_NUMBER="0544 124 56 78"
REQUIRED_FILE_XPATH="//span[text()='Doldurulması zorunlu alan*']"
RECORD_BUTTON_XPATH="//button[@class='btn btn-primary py-2 mb-3 d-inline-block mobil-btn']"
BIRTHDATE_NAME="birthday"
SCRIPT_LOCATION="window.scrollTo(0,500)"
SCRIPT_LOCATION2="window.scrollTo(500,0)"
SCRIPT_LOCATION3="window.scrollTo(500,100)"
SCRIPT_LOCATION4="window.scrollTo(0,600)"
REQUIRED_TEXT="Doldurulması zorunlu alan*"
BIRTHDATE="01.01.1991"
REQUIRED_FIELDS_XPATH="(//span[@class='text-danger'])[2]"
REQUIRED_FIELDS_TEXT="Aboneliklerde fatura için doldurulması zorunlu alan"
LESS_IDENTIFIER_TEXT="TC Kimlik Numarası 11 Haneden Az olamaz"
MORE_IDENTIFIER_TEXT="TC Kimlik Numarası 11 Haneden Fazla olamaz"
MORE_IDENTIFIER_REQUIRED=".text-danger:nth-child(4)"
LESS_IDENTIFIER="1234"
MORE_IDENTIFIER="12345678997654"
IDENTIFIER_NAME="identifier"
VALID_IDENTIFIER="37843088124"
INVALID_IDENTIFIER="378843088123"
COUNTRY_NAME="country" 
LESS_COUNTRY_NAME="e"
MORE_COUNTRY_NAME="TürkiyeTürkiyeTürkiyeTürkiyeTürkiyeTürkiyeTürkiyeTürkiye"
LESS_COUNTRY_TEXT="En az 2 karakter girmelisiniz"
MORE_COUNTRY_TEXT="En fazla 30 karakter girebilirsiniz"
REQUIRED_FIELDS_COUNTRY_CSS=".col-12:nth-child(8) > .text-danger"
VALID_COUNTRY="Türkiye"
CITY_NAME="city"
CHOOSE_CITY_TEXT="İl Seçiniz"
REQUIRED_FIELDS_CITY_CSS=".col-12:nth-child(9) > .text-danger"
REQUIRED_FIELDS_DISTRICT_CSS=".col-12:nth-child(10) > .text-danger"
DISTRICT_NAME="district"
VALID_CITY_TEXT="İstanbul"
VALID_DISTRICT_TEXT="Beylikdüzü"
VALID_NEIGHBOURHOOD="Hürriyet Mahallesi"
INVALID_NEIGHBOURHOOD="Hürriyetttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttt"
NEIGHBOURHOOD_NAME="address"
REQUIRED_FIELDS_NEIGHBOURHOOD_CSS=".col-12:nth-child(11) > .text-danger"
REQUIRED_FIELDS_ABOUT_CSS=".col-12:nth-child(12) > .text-danger"
REQUIRED_FIELDS_NEIGHBOURHOOD_TEXT= "En fazla 200 karakter girebilirsiniz"
REQUIRED_FIELDS_ABOUT_TEXT= "En fazla 300 karakter girebilirsiniz"
ABOUT_ME_CSS=".col-12:nth-child(12) > .form-control"
VALID_ABOUT_ME="Çiçekleri Ve Bahar Mevsimini çok severim"
INVALID_ABOUT_ME="alertttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttt"
SUCCESS_WARNING_MESSAGE="• Bilgileriniz başarıyla güncellendi."
UNSUCCESS_WARNING_MESSAGE="• Kimlik bilgilerinizi hatalı girdiniz."
VALID_NAME="Esra"