LOGIN_URL="https://tobeto.com/giris"
PROFILE_SUMMARY_CSS="span:nth-child(3) > svg"
PROFILE_INFO_XPATH="(//a[@class='dropdown-item profil-dropdown'])[1]"
MY_PERSONAL_INFO_XPATH="(//span[@class='sidebar-text'])[1]"
MY_EXPERIENCE_XPATH="(//span[@class='sidebar-text'])[2]"
MY_EDUCATIONLIFE_XPATH="(//span[@class='sidebar-text'])[3]"
MY_COMPETENCIES_XPATH="(//span[@class='sidebar-text'])[4]"
MY_CERTIFICATEDS_XPATH="(//span[@class='sidebar-text'])[5]"
MY_MEDIA_ACCOUNT_XPATH="(//span[@class='sidebar-text'])[6]"
MY_FOREIGN_LANG_XPATH="(//span[@class='sidebar-text'])[7]"
SETTINGS_XPATH="(//span[@class='sidebar-text'])[8]"
MY_PERSONAL_URL="https://tobeto.com/profilim/profilimi-duzenle/kisisel-bilgilerim"
MY_EXPERIENCE_URL="https://tobeto.com/profilim/profilimi-duzenle/deneyimlerim"
MY_EDUCATIONLIFE_URL="https://tobeto.com/profilim/profilimi-duzenle/egitim-hayatim"
MY_COMPETENCIES_URL="https://tobeto.com/profilim/profilimi-duzenle/yetkinliklerim"
MY_CERTIFICATEDS_URL="https://tobeto.com/profilim/profilimi-duzenle/sertifikalarim"
MY_MEDIA_ACCOUNT_URL="https://tobeto.com/profilim/profilimi-duzenle/medya-hesaplarim"
MY_FOREIGN_LANG_URL="https://tobeto.com/profilim/profilimi-duzenle/yabanci-dil"
SETTINGS_URL="https://tobeto.com/profilim/profilimi-duzenle/ayarlar"