BASE_URL="https://tobeto.com"
PROFIL_BILGILERIM_URL="https://tobeto.com/profilim/profilimi-duzenle/kisisel-bilgilerim"
LOGIN_TOBETO_XLSX="data/loginTobeto.xlsx"
LOGIN_BUTTON_XPATH="//*[@id='offcanvasExample']/div[2]/div[2]/div/a[1]"
LOGIN_BUTTON_CLICK_XPATH="//*[@id='__next']/div/main/section/div/div/div[1]/div/form/button"
E_MAIL= "email"
PASSWORD_NAME = "password"
PROFILIM="//*[@id='__next']/div/nav/div[1]/ul/li[2]"
MEDYA_HESAPLARIM="//*[@id='__next']/div/main/section/div/div/div[1]/div/a[6]"
MEDYA_HESAP_SECIM="//*[@id='__next']/div/main/section/div/div/div[2]/div/form/div/div[1]/select"
GITHUB_SECIM="//*[@id='__next']/div/main/section/div/div/div[2]/div/form/div/div[1]/select/option[7]"
GITHUB_ADRES="//*[@id='__next']/div/main/section/div/div/div[2]/div/form/div/div[2]/input"
KAYDET_BUTON="//*[@id='__next']/div/main/section/div/div/div[2]/div/form/button"
GUNCELLE_BUTONU="//*[@id='__next']/div/main/section/div/div/div[2]/div[2]/div/btn[2]"
GUNCELLENECEK_METIN=".modal-footer .form-control"
GUNCELLEME_GIRILEN_METIN=".modal-footer .form-control"
MEDYA_HESAP_SIL_BUTON="//*[@id='__next']/div/main/section/div/div/div[2]/div[2]/div/btn[1]"
SIL_EVET_BUTON="/html/body/div[3]/div/div/div/div/div/div[2]/button[2]"
GUNCELLE_BUTON="/html/body/div[3]/div/div/div[2]/button[1]"
FORBIDDEN="//*[@id='__next']/div/div[2]"

